#!/usr/bin/env python

## @author tarun.murala

# Either create a Symlink or Use the GitHooks Config Dir

import subprocess
import re
import json
import requests

SNOW_URL = 'http://localhost:8080/api/now/commit_integration_api'
SNOW_USER_NAME = 'admin'
SNOW_USER_PASS = 'admin'
INCLUDE_DIFF = True;

DIFF_TREE_RE = re.compile("^:(?P<src_mode>[0-9]{6}) (?P<dst_mode>[0-9]{6}) (?P<src_hash>[0-9a-f]{7,40}) (?P<dst_hash>[0-9a-f]{7,40}) (?P<status>[ADMTUX]|[CR][0-9]{1,3})\s+(?P<file1>\S+)(?:\s+(?P<file2>\S+))?$", re.MULTILINE)

response_data = {}
response_data['source_versioning'] = 'GIT'
response_data['message'] = ''
response_data['branch'] = ''
response_data['committer'] = ''
response_data['commit_id'] = ''
response_data['repo_url'] = ''
response_data['added_files'] = []
response_data['updated_files'] = []
response_data['renamed_files'] = []
response_data['deleted_files'] = []

def run_git(args):
    args = ['git'] + args
    git = subprocess.Popen(args, stdout = subprocess.PIPE)
    details = git.stdout.read()
    details = details.decode("utf-8").strip()
    return details

def get_message(commit):
    return run_git(['log', '--format=%B', '-n', '1', commit])

def get_repo():
    return run_git(['config', '--get', 'remote.origin.url'])

def get_commiter(commit):
    return run_git(['log', "--format='%ae'", commit+"^!"])

def get_actual_file_name(file_name):
    file_name_parts = file_name.strip().split('/')
    return file_name_parts[len(file_name_parts) - 1].encode("ascii")

def generate_diff_file(branch_name, commit_range, file_name):
    actual_file_name = get_actual_file_name(file_name)
    ref_name = (branch_name + ':' + file_name).encode("ascii")
    return run_git(['diff', commit_range, '--', file_name])

def filter_diff(diff):
    lines = diff.split('\n')
    s = 0
    while s < len(lines):
        if "@@" not in lines[s]:
            s = s+1
            continue
        else:
            break;

    filtered_diff = lines[s:]
    # print filtered_diff
    return "\n".join(filtered_diff);

def add_to_new_file(commit_sha, commit_range, file_name):
    print "Reading NEW File -> " + file_name
    branch_name = get_branch_name(commit_sha)
    output = generate_diff_file(branch_name, commit_range, file_name)
    filtered_output = filter_diff(output);
    added_file = {'file_name': file_name}
    if INCLUDE_DIFF:
        added_file['diff'] = filtered_output

    response_data['added_files'].append(added_file);

def add_to_updated_file(commit_sha, commit_range, file_name):
    print "Reading MODIFIED File -> " + file_name
    branch_name = get_branch_name(commit_sha)
    output = generate_diff_file(branch_name, commit_range, file_name)
    filtered_output = filter_diff(output);
    updated_file = {'file_name': file_name}
    if INCLUDE_DIFF:
        updated_file['diff'] = filtered_output

    response_data['updated_files'].append(updated_file);
    

def add_to_renamed_file(commit_sha, commit_range, file_name):
    print "Reading RENAMED File -> " + file_name
    branch_name = get_branch_name(commit_sha)
    # output = generate_diff_file(branch_name, commit_range, file_name)

    renamed_file = {'file_name': file_name}
    response_data['renamed_files'].append(renamed_file);

def add_to_deleted_file(commit_sha, commit_range, file_name):
    print "Reading RENAMED File -> " + file_name
    branch_name = get_branch_name(commit_sha)
    # output = generate_diff_file(branch_name, commit_range, file_name)

    deleted_file = {'file_name': file_name}
    response_data['deleted_files'].append(deleted_file);


def get_branch_name(commit):
    branches = run_git(['branch', '--contains', commit]).split('\n')
    CURR_BRANCH_RE = re.compile('^\* \w+$')
    curr_branch = None

    if len(branches) > 1:
        on_master = False
        for branch in branches:
            if CURR_BRANCH_RE.match(branch):
                curr_branch = branch.strip('* \n')
            elif branch.strip() == 'master':
                on_master = True

        if curr_branch is None and on_master:
            curr_branch = 'master'

    if curr_branch is None:
        curr_branch = branches[0].strip('* \n')

    base_ref = 'refs/heads/%s' % curr_branch
    return base_ref

def call_snow_instance(old, new, head_commit=False):
    if re.match("^0+$", old):
        if not head_commit:
            return []

        commit_range = '%s~1..%s' % (new, new)
    else:
        commit_range = '%s..%s' % (old, new)

    response_data['message'] = get_message(new)
    # Can use the ref instead for branch
    response_data['branch'] = get_branch_name(new)
    response_data['committer'] = get_commiter(new)
    response_data['commit_id'] = new
    response_data['repo_url'] = get_repo()
    revs = run_git(['rev-list', '--pretty=medium', '--reverse', commit_range])
    # print revs
    sections = revs.split('\n\n')

    s = 0
    while s < len(sections):
        lines = sections[s].split('\n')
        commit_sha = lines[0].strip().split(' ')[1].encode("ascii")
        output = run_git(['diff-tree', '-r', '-C', '%s' % commit_sha])
        # print output
        for i in DIFF_TREE_RE.finditer(output):
            item = i.groupdict()
            status = item['status']
            file_name = item['file1'];
            # print item
            # print status
            # print file_name
            if item['status'] == 'A':      
                add_to_new_file(commit_sha, commit_range, file_name)
            elif item['status'] == 'M':    
                add_to_updated_file(commit_sha, commit_range, file_name)
            elif item['status'] == 'R':    
                add_to_renamed_file(commit_sha, commit_range, file_name)
            elif item['status'] == 'D':    
                add_to_deleted_file(commit_sha, commit_range, file_name)
            
        s+=2

    json_data = json.dumps(response_data)
    print json_data
    resp = requests.post(SNOW_URL, data=json_data, auth=(SNOW_USER_NAME, SNOW_USER_PASS))
    print resp


## MAIN CODE
# if __name__ == "__main__":
#     for line in sys.stdin:
#         old, new, ref = line.strip().split(' ')
#         print "old -> " + old + "| new -> " + new + " | ref -> " + ref
#         call_snow_instance(old, new, ref)

## TEST Code - After seeding the test files
call_snow_instance('ba398801e018f5e1be53a3a1d3533a04f3a0c56f', 'a2b1adeca4b1d908cd0a9517e4dc39dc73c7b324')
